SELECT 1 FROM sysibm.sysdummy1;

DROP TABLE TMP_TABLE_A;
DROP TABLE TMP_TABLE_B;

CREATE TABLE TMP_TABLE_A (UID_VALUE VARCHAR(20), MESSAGE VARCHAR(50), PRIMARY KEY(UID_VALUE));
CREATE TABLE TMP_TABLE_B (UID_VALUE VARCHAR(20), MESSAGE VARCHAR(50), PRIMARY KEY(UID_VALUE));

select * from TMP_TABLE_A;
select * from TMP_TABLE_B;

